/**
 * Utility helpers for text formatting within the extension UI.
 */

/**
 * Truncate voucher codes to show only the prefix (up to the first 6 chars after 0x)
 * and the last 6 characters, keeping the core structure intact.
 *
 * Example:
 *   S-1000000000-6-0x332ea3b48c67d5...0b29adf
 *
 * @param voucherCode Full voucher code string generated by the app
 * @param extraChars Number of characters to show after the `0x` prefix and at the end
 */
export function truncateVoucherCode(voucherCode: string, extraChars = 6): string {
  if (!voucherCode) {
    return '';
  }

  const parts = voucherCode.split('-');
  if (parts.length < 4) {
    return voucherCode;
  }

  const prefix = parts.slice(0, 3).join('-');
  const hexPart = parts.slice(3).join('-');

  const prefixWithHex = `${prefix}-`;

  if (!hexPart.startsWith('0x') || hexPart.length <= 2 + extraChars * 2) {
    return voucherCode;
  }

  const leading = hexPart.slice(0, 2); // include 0x
  const trailing = hexPart.slice(-extraChars);

  return `${prefixWithHex}${leading}...${trailing}`;
}
